# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "abacaxi"
    ports:
      - "5432:5432"
